changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - feature
    - title: '🐛 Fixes'
      labels:
        - bug
    - title: '♻️ Refactor'
      labels:
        - refactor
    - title: '📦 Dependencies'
      labels:
        - renovate/deps
