# Dependency Properties
jda.version=5.0.0-beta.24
rome.version=2.1.0
gson.version=2.11.0
lombok.version=1.18.34
unirest.version=4.4.0
caffeine.version=3.1.8
hikaricp.version=5.1.0
litecommands.version=3.4.2
source.query.version=1.2.2
xerial.sqlite.version=3.46.0.0
okaeri.configs.version=5.0.2
logback.classic.version=1.5.6
jetbrains.annotations.version=24.1.0

# Gradle Properties
org.gradle.caching=true
org.gradle.parallel=true
