[versions]
jda-core = "6.4.1"
jda-commands = "5.0.0"

gson = "2.13.2"
guava = "33.6.0-jre"
caffeine = "3.2.3"

sqlite = "3.53.0.0"
hikaricp = "7.0.2"
hibernate = "7.3.2.Final"
jakarta = "3.2.0"

oshi = "6.12.0"
unirest = "4.8.1"
logback = "1.5.32"
apache-commons = "3.20.0"

lombok = "1.18.46"
jetbrains-annotations = "26.1.0"

[libraries]
jda-core = { group = "net.dv8tion", name = "JDA", version.ref = "jda-core" }
jda-commands = { group = "io.github.kaktushose", name = "jda-commands", version.ref = "jda-commands" }

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }

sqlite-driver = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite" }
hikaricp = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikaricp" }
hibernate-core = { group = "org.hibernate.orm", name = "hibernate-core", version.ref = "hibernate" }
hibernate-hikaricp = { group = "org.hibernate.orm", name = "hibernate-hikaricp", version.ref = "hibernate" }
hibernate-community-dialects = { group = "org.hibernate.orm", name = "hibernate-community-dialects", version.ref = "hibernate" }
jakarta-persistence = { group = "jakarta.persistence", name = "jakarta.persistence-api", version.ref = "jakarta" }

oshi-core = { group = "com.github.oshi", name = "oshi-core-java25", version.ref = "oshi" }
unirest-java-core = { group = "com.konghq", name = "unirest-java-core", version.ref = "unirest" }
unirest-modules-gson = { group = "com.konghq", name = "unirest-modules-gson", version.ref = "unirest" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
apache-commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "apache-commons" }

lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations" }
